name: simplify_commerce
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://pub.dartlang.org

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: ">=2.10.0"


dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  import_js_library: ^1.0.2
  js: ^0.6.4


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
